// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1sAjkry0eyDKrEIu3FyNZI8WtIuLujU',
    appId: '1:444475836276:web:10c337425529364ff1ce21',
    messagingSenderId: '444475836276',
    projectId: 'ciclistas-2dcd0',
    authDomain: 'ciclistas-2dcd0.firebaseapp.com',
    storageBucket: 'ciclistas-2dcd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WqcJ-A6FGAMl0nd_BRUKlkwKJP6HeeA',
    appId: '1:444475836276:android:a87e839c96b16e35f1ce21',
    messagingSenderId: '444475836276',
    projectId: 'ciclistas-2dcd0',
    storageBucket: 'ciclistas-2dcd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAECA1i71DecQcR2lPk-ul26e5gaDxh3Us',
    appId: '1:444475836276:ios:07d04dd82a1a8a7cf1ce21',
    messagingSenderId: '444475836276',
    projectId: 'ciclistas-2dcd0',
    storageBucket: 'ciclistas-2dcd0.appspot.com',
    iosClientId: '444475836276-smov52gqequ3qmrkfe7mg86nvtgkn0va.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciclistas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAECA1i71DecQcR2lPk-ul26e5gaDxh3Us',
    appId: '1:444475836276:ios:07d04dd82a1a8a7cf1ce21',
    messagingSenderId: '444475836276',
    projectId: 'ciclistas-2dcd0',
    storageBucket: 'ciclistas-2dcd0.appspot.com',
    iosClientId: '444475836276-smov52gqequ3qmrkfe7mg86nvtgkn0va.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciclistas',
  );
}
